//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 12:04:09 AM MSK 
//


package ru.yandex.pogoda.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.yandex.pogoda.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ForecastDayDayPartWeatherTypeTt_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_tt");
    private final static QName _ForecastDayDayPartImageV3_QNAME = new QName("http://weather.yandex.ru/forecast", "image-v3");
    private final static QName _ForecastDayDayPartWeatherTypeTr_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_tr");
    private final static QName _ForecastDayDayPartImageV2_QNAME = new QName("http://weather.yandex.ru/forecast", "image-v2");
    private final static QName _ForecastDayDayPartWeatherTypeShortKz_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_short_kz");
    private final static QName _ForecastDayDayPartPressure_QNAME = new QName("http://weather.yandex.ru/forecast", "pressure");
    private final static QName _ForecastDayDayPartWindDirection_QNAME = new QName("http://weather.yandex.ru/forecast", "wind_direction");
    private final static QName _ForecastDayDayPartWeatherCondition_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_condition");
    private final static QName _ForecastDayDayPartImage_QNAME = new QName("http://weather.yandex.ru/forecast", "image");
    private final static QName _ForecastDayDayPartMslpPressure_QNAME = new QName("http://weather.yandex.ru/forecast", "mslp_pressure");
    private final static QName _ForecastDayDayPartWeatherTypeShortTr_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_short_tr");
    private final static QName _ForecastDayDayPartWeatherTypeKz_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_kz");
    private final static QName _ForecastDayDayPartWeatherTypeShortTt_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_short_tt");
    private final static QName _ForecastDayDayPartTemperatureFrom_QNAME = new QName("http://weather.yandex.ru/forecast", "temperature_from");
    private final static QName _ForecastDayDayPartTemperatureTo_QNAME = new QName("http://weather.yandex.ru/forecast", "temperature_to");
    private final static QName _ForecastDayDayPartWeatherTypeShortUa_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_short_ua");
    private final static QName _ForecastDayDayPartWeatherType_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type");
    private final static QName _ForecastDayDayPartWeatherTypeShort_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_short");
    private final static QName _ForecastDayDayPartWeatherTypeBy_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_by");
    private final static QName _ForecastDayDayPartTemperatureData_QNAME = new QName("http://weather.yandex.ru/forecast", "temperature-data");
    private final static QName _ForecastDayDayPartWindSpeed_QNAME = new QName("http://weather.yandex.ru/forecast", "wind_speed");
    private final static QName _ForecastDayDayPartHumidity_QNAME = new QName("http://weather.yandex.ru/forecast", "humidity");
    private final static QName _ForecastDayDayPartTemperature_QNAME = new QName("http://weather.yandex.ru/forecast", "temperature");
    private final static QName _ForecastDayDayPartWeatherTypeUa_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_ua");
    private final static QName _ForecastDayDayPartWeatherTypeShortBy_QNAME = new QName("http://weather.yandex.ru/forecast", "weather_type_short_by");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.yandex.pogoda.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Forecast }
     * 
     */
    public Forecast createForecast() {
        return new Forecast();
    }

    /**
     * Create an instance of {@link Forecast.Day }
     * 
     */
    public Forecast.Day createForecastDay() {
        return new Forecast.Day();
    }

    /**
     * Create an instance of {@link Forecast.Day.Hour }
     * 
     */
    public Forecast.Day.Hour createForecastDayHour() {
        return new Forecast.Day.Hour();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart }
     * 
     */
    public Forecast.Day.DayPart createForecastDayDayPart() {
        return new Forecast.Day.DayPart();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.TemperatureData }
     * 
     */
    public Forecast.Day.DayPart.TemperatureData createForecastDayDayPartTemperatureData() {
        return new Forecast.Day.DayPart.TemperatureData();
    }

    /**
     * Create an instance of {@link Forecast.Day.Biomet }
     * 
     */
    public Forecast.Day.Biomet createForecastDayBiomet() {
        return new Forecast.Day.Biomet();
    }

    /**
     * Create an instance of {@link Forecast.Informer }
     * 
     */
    public Forecast.Informer createForecastInformer() {
        return new Forecast.Informer();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday }
     * 
     */
    public Forecast.Yesterday createForecastYesterday() {
        return new Forecast.Yesterday();
    }

    /**
     * Create an instance of {@link Forecast.Fact }
     * 
     */
    public Forecast.Fact createForecastFact() {
        return new Forecast.Fact();
    }

    /**
     * Create an instance of {@link Forecast.Day.MoonPhase }
     * 
     */
    public Forecast.Day.MoonPhase createForecastDayMoonPhase() {
        return new Forecast.Day.MoonPhase();
    }

    /**
     * Create an instance of {@link Forecast.Day.Hour.WeatherCondition }
     * 
     */
    public Forecast.Day.Hour.WeatherCondition createForecastDayHourWeatherCondition() {
        return new Forecast.Day.Hour.WeatherCondition();
    }

    /**
     * Create an instance of {@link Forecast.Day.Hour.Image }
     * 
     */
    public Forecast.Day.Hour.Image createForecastDayHourImage() {
        return new Forecast.Day.Hour.Image();
    }

    /**
     * Create an instance of {@link Forecast.Day.Hour.ImageV2 }
     * 
     */
    public Forecast.Day.Hour.ImageV2 createForecastDayHourImageV2() {
        return new Forecast.Day.Hour.ImageV2();
    }

    /**
     * Create an instance of {@link Forecast.Day.Hour.ImageV3 }
     * 
     */
    public Forecast.Day.Hour.ImageV3 createForecastDayHourImageV3() {
        return new Forecast.Day.Hour.ImageV3();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.WeatherCondition }
     * 
     */
    public Forecast.Day.DayPart.WeatherCondition createForecastDayDayPartWeatherCondition() {
        return new Forecast.Day.DayPart.WeatherCondition();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.Image }
     * 
     */
    public Forecast.Day.DayPart.Image createForecastDayDayPartImage() {
        return new Forecast.Day.DayPart.Image();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.ImageV2 }
     * 
     */
    public Forecast.Day.DayPart.ImageV2 createForecastDayDayPartImageV2() {
        return new Forecast.Day.DayPart.ImageV2();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.ImageV3 }
     * 
     */
    public Forecast.Day.DayPart.ImageV3 createForecastDayDayPartImageV3() {
        return new Forecast.Day.DayPart.ImageV3();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.Pressure }
     * 
     */
    public Forecast.Day.DayPart.Pressure createForecastDayDayPartPressure() {
        return new Forecast.Day.DayPart.Pressure();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.MslpPressure }
     * 
     */
    public Forecast.Day.DayPart.MslpPressure createForecastDayDayPartMslpPressure() {
        return new Forecast.Day.DayPart.MslpPressure();
    }

    /**
     * Create an instance of {@link Forecast.Day.DayPart.TemperatureData.Avg }
     * 
     */
    public Forecast.Day.DayPart.TemperatureData.Avg createForecastDayDayPartTemperatureDataAvg() {
        return new Forecast.Day.DayPart.TemperatureData.Avg();
    }

    /**
     * Create an instance of {@link Forecast.Day.Biomet.Message }
     * 
     */
    public Forecast.Day.Biomet.Message createForecastDayBiometMessage() {
        return new Forecast.Day.Biomet.Message();
    }

    /**
     * Create an instance of {@link Forecast.Informer.Temperature }
     * 
     */
    public Forecast.Informer.Temperature createForecastInformerTemperature() {
        return new Forecast.Informer.Temperature();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.Station }
     * 
     */
    public Forecast.Yesterday.Station createForecastYesterdayStation() {
        return new Forecast.Yesterday.Station();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.Temperature }
     * 
     */
    public Forecast.Yesterday.Temperature createForecastYesterdayTemperature() {
        return new Forecast.Yesterday.Temperature();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.WeatherCondition }
     * 
     */
    public Forecast.Yesterday.WeatherCondition createForecastYesterdayWeatherCondition() {
        return new Forecast.Yesterday.WeatherCondition();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.Image }
     * 
     */
    public Forecast.Yesterday.Image createForecastYesterdayImage() {
        return new Forecast.Yesterday.Image();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.ImageV2 }
     * 
     */
    public Forecast.Yesterday.ImageV2 createForecastYesterdayImageV2() {
        return new Forecast.Yesterday.ImageV2();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.ImageV3 }
     * 
     */
    public Forecast.Yesterday.ImageV3 createForecastYesterdayImageV3() {
        return new Forecast.Yesterday.ImageV3();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.Pressure }
     * 
     */
    public Forecast.Yesterday.Pressure createForecastYesterdayPressure() {
        return new Forecast.Yesterday.Pressure();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.MslpPressure }
     * 
     */
    public Forecast.Yesterday.MslpPressure createForecastYesterdayMslpPressure() {
        return new Forecast.Yesterday.MslpPressure();
    }

    /**
     * Create an instance of {@link Forecast.Yesterday.Season }
     * 
     */
    public Forecast.Yesterday.Season createForecastYesterdaySeason() {
        return new Forecast.Yesterday.Season();
    }

    /**
     * Create an instance of {@link Forecast.Fact.Station }
     * 
     */
    public Forecast.Fact.Station createForecastFactStation() {
        return new Forecast.Fact.Station();
    }

    /**
     * Create an instance of {@link Forecast.Fact.Temperature }
     * 
     */
    public Forecast.Fact.Temperature createForecastFactTemperature() {
        return new Forecast.Fact.Temperature();
    }

    /**
     * Create an instance of {@link Forecast.Fact.WeatherCondition }
     * 
     */
    public Forecast.Fact.WeatherCondition createForecastFactWeatherCondition() {
        return new Forecast.Fact.WeatherCondition();
    }

    /**
     * Create an instance of {@link Forecast.Fact.Image }
     * 
     */
    public Forecast.Fact.Image createForecastFactImage() {
        return new Forecast.Fact.Image();
    }

    /**
     * Create an instance of {@link Forecast.Fact.ImageV2 }
     * 
     */
    public Forecast.Fact.ImageV2 createForecastFactImageV2() {
        return new Forecast.Fact.ImageV2();
    }

    /**
     * Create an instance of {@link Forecast.Fact.ImageV3 }
     * 
     */
    public Forecast.Fact.ImageV3 createForecastFactImageV3() {
        return new Forecast.Fact.ImageV3();
    }

    /**
     * Create an instance of {@link Forecast.Fact.Pressure }
     * 
     */
    public Forecast.Fact.Pressure createForecastFactPressure() {
        return new Forecast.Fact.Pressure();
    }

    /**
     * Create an instance of {@link Forecast.Fact.MslpPressure }
     * 
     */
    public Forecast.Fact.MslpPressure createForecastFactMslpPressure() {
        return new Forecast.Fact.MslpPressure();
    }

    /**
     * Create an instance of {@link Forecast.Fact.Season }
     * 
     */
    public Forecast.Fact.Season createForecastFactSeason() {
        return new Forecast.Fact.Season();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_tt", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeTt(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeTt_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.ImageV3 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "image-v3", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.ImageV3> createForecastDayDayPartImageV3(Forecast.Day.DayPart.ImageV3 value) {
        return new JAXBElement<Forecast.Day.DayPart.ImageV3>(_ForecastDayDayPartImageV3_QNAME, Forecast.Day.DayPart.ImageV3 .class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_tr", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeTr(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeTr_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.ImageV2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "image-v2", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.ImageV2> createForecastDayDayPartImageV2(Forecast.Day.DayPart.ImageV2 value) {
        return new JAXBElement<Forecast.Day.DayPart.ImageV2>(_ForecastDayDayPartImageV2_QNAME, Forecast.Day.DayPart.ImageV2 .class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_short_kz", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeShortKz(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeShortKz_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.Pressure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "pressure", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.Pressure> createForecastDayDayPartPressure(Forecast.Day.DayPart.Pressure value) {
        return new JAXBElement<Forecast.Day.DayPart.Pressure>(_ForecastDayDayPartPressure_QNAME, Forecast.Day.DayPart.Pressure.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "wind_direction", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWindDirection(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWindDirection_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.WeatherCondition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_condition", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.WeatherCondition> createForecastDayDayPartWeatherCondition(Forecast.Day.DayPart.WeatherCondition value) {
        return new JAXBElement<Forecast.Day.DayPart.WeatherCondition>(_ForecastDayDayPartWeatherCondition_QNAME, Forecast.Day.DayPart.WeatherCondition.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "image", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.Image> createForecastDayDayPartImage(Forecast.Day.DayPart.Image value) {
        return new JAXBElement<Forecast.Day.DayPart.Image>(_ForecastDayDayPartImage_QNAME, Forecast.Day.DayPart.Image.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.MslpPressure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "mslp_pressure", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.MslpPressure> createForecastDayDayPartMslpPressure(Forecast.Day.DayPart.MslpPressure value) {
        return new JAXBElement<Forecast.Day.DayPart.MslpPressure>(_ForecastDayDayPartMslpPressure_QNAME, Forecast.Day.DayPart.MslpPressure.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_short_tr", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeShortTr(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeShortTr_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_kz", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeKz(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeKz_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_short_tt", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeShortTt(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeShortTt_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "temperature_from", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Byte> createForecastDayDayPartTemperatureFrom(Byte value) {
        return new JAXBElement<Byte>(_ForecastDayDayPartTemperatureFrom_QNAME, Byte.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "temperature_to", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Byte> createForecastDayDayPartTemperatureTo(Byte value) {
        return new JAXBElement<Byte>(_ForecastDayDayPartTemperatureTo_QNAME, Byte.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_short_ua", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeShortUa(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeShortUa_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherType(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherType_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_short", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeShort(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeShort_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_by", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeBy(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeBy_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast.Day.DayPart.TemperatureData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "temperature-data", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Forecast.Day.DayPart.TemperatureData> createForecastDayDayPartTemperatureData(Forecast.Day.DayPart.TemperatureData value) {
        return new JAXBElement<Forecast.Day.DayPart.TemperatureData>(_ForecastDayDayPartTemperatureData_QNAME, Forecast.Day.DayPart.TemperatureData.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "wind_speed", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Float> createForecastDayDayPartWindSpeed(Float value) {
        return new JAXBElement<Float>(_ForecastDayDayPartWindSpeed_QNAME, Float.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "humidity", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Byte> createForecastDayDayPartHumidity(Byte value) {
        return new JAXBElement<Byte>(_ForecastDayDayPartHumidity_QNAME, Byte.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "temperature", scope = Forecast.Day.DayPart.class)
    public JAXBElement<Byte> createForecastDayDayPartTemperature(Byte value) {
        return new JAXBElement<Byte>(_ForecastDayDayPartTemperature_QNAME, Byte.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_ua", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeUa(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeUa_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://weather.yandex.ru/forecast", name = "weather_type_short_by", scope = Forecast.Day.DayPart.class)
    public JAXBElement<String> createForecastDayDayPartWeatherTypeShortBy(String value) {
        return new JAXBElement<String>(_ForecastDayDayPartWeatherTypeShortBy_QNAME, String.class, Forecast.Day.DayPart.class, value);
    }

}
