//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 08:39:51 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://weather.yandex.ru/forecast", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.yandex.pogoda.ws;
